name: Docker - Build and push latest

on:
  push:
    branches: ["**"]
    tags-ignore: ["release-*"]

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example
  BUILD_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example:buildimage

jobs:
  build-latest:
    name: Build Block
    runs-on: self-hosted
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to registry
        id: build
        env:
          APP_IMAGE_URI: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
        run: |
          chmod +x build.sh
          ./build.sh
          echo "image-uri=$APP_IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Built Succesfully"
        shell: bash

  push-block:
    name: Push Block to Contensis
    runs-on: self-hosted
    needs: build-latest

    steps:
      - name: Push block to website on leif
        uses: contensis/block-push@v1
        with:
          block-id: leif-blogs
          auto-release: true
          image-uri: ${{ needs.build-latest.outputs.image-uri }}
          alias: leif
          project-id: website
          client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
          tag-repo: true
          git-token: ${{ secrets.GITHUB_TOKEN }}
