name: Docker - Build and push latest

on:
  push:
    branches: [ "**" ]
    tags-ignore: [ "release-*" ]
  workflow_dispatch:


env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example
  BUILD_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example:buildimage
  CONTENSIS_CLIENT_ID: 8c880e9e-503d-44d3-9373-94a717077c70
  CONTENSIS_SHARED_SECRET: f2d3f9bb04fd46e79414b06282024405-0444a63a7b76439b85d11f3cfb6f5b14-71693c1af749456994d7970f2b8e7af7

jobs:
  build-latest:
    name: Build Block
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into the container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to the registry
        id: build
        env:
          APP_IMAGE_URI: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
        run: |
          chmod +x build.sh
          ./build.sh
          echo "image-uri=$APP_IMAGE_URI" >> $GITHUB_OUTPUT
          echo "Built Successfully"
        shell: bash
  deploy:
    name: Push block to Contensis
    runs-on: ubuntu-latest
    needs: build-latest
    steps:
      - name: Push block to Contensis
        id: push-block
        uses: contensis/block-push@v1
        with:
          block-id: my-dotnet-block
          alias: velocity-blocks
          project-id: leif01
          client-id: ${{ env.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ env.CONTENSIS_SHARED_SECRET }}
          image-uri: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
