name: Docker - Build and push latest

on:
  push:
    branches: ["**"]
    tags-ignore: ["release-*"]
  pull_request:
    branches: ["**"]

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/razor-example

jobs:
  build-latest:
    name: Docker build latest code
    runs-on: ubuntu-latest
    outputs:
      image-uri: ${{ steps.build.outputs.image-uri }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image, tag and push to registry
        id: build
        run: |
          BUILD_IMAGE_URI=${{ env.APP_IMAGE }}:build-${{ github.run_number }}
          docker pull ${{ env.APP_IMAGE }}:latest || true
          echo "{\"commitRef\":\"${{ github.sha }}\",\"pipelineIID\":\"null\",\"pipelineUrl\":\"${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}\",\"buildNo\":\"${{ github.run_number }}\",\"branchName\":\"${{ github.ref_name }}\",\"registryImage\":\"${{ env.APP_IMAGE }}\"}" > version.json
          docker build --force-rm --cache-from ${{ env.APP_IMAGE }}:latest -t ${{ env.APP_IMAGE }}:latest -f docker/build.DockerFile .
          docker push ${{ env.APP_IMAGE }}:latest
          docker tag ${{ env.APP_IMAGE }}:latest BUILD_IMAGE_URI
          docker push BUILD_IMAGE_URI
          echo "image-uri=$BUILD_IMAGE_URI" >> $GITHUB_OUTPUT

  push-block:
    name: Push Contensis block
    runs-on: ubuntu-latest
    needs: build-latest

    steps:
      - name: Push block to website on leif
        uses: contensis/block-push@v1
        with:
          block-id: leif-blogs
          auto-release: true
          image-uri: ${{ needs.build-latest.outputs.image-uri }}
          alias: leif
          project-id: website
          client-id: ${{ secrets.CONTENSIS_CLIENT_ID }}
          shared-secret: ${{ secrets.CONTENSIS_SHARED_SECRET }}
          tag-repo: true
          git-token: ${{ secrets.GITHUB_TOKEN }}
